{% set version = "0.29.3" %}

{% set python_min = python_min | default("3.12") %}

package:
  name: pyodide-build
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyodide-build/pyodide_build-{{ version }}.tar.gz
  sha256: 7da6e59dbf8d7bce2b98d85417afe742d3d712df77fea415d352f646ed44207e
  patches:
    # this _should_ fail if the version of cmake changes below
    - 0000-no-cmake-from-pip.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - auditwheel-emscripten >=0.0.9,<0.1.0
    - cmake >=3.24
    - packaging
    - pydantic >=2,<3
    - pyodide-cli >=0.2.1,<0.3.dev0
    - python >={{ python_min }}
    - python-build >=1.2.0,<1.3.dev0
    - pyodide-lock ==0.1.0a7
    - requests
    - resolvelib
    - rich
    - ruamel.yaml
    - typer
    - unearth >=0.6,<1.dev0
    - virtualenv
    - wheel

test:
  imports:
    - pyodide_build
  requires:
    - pip
    - python {{ python_min }}
    - m2-grep  # [win]
  commands:
    - pip check
    - pyodide build-recipes --help
    - pyodide skeleton --help
    - pyodide config --help
    - python -c "v = __import__('pyodide_build').__version__; print(v); assert v == '{{ version }}'"

about:
  home: https://github.com/pyodide/pyodide-build
  summary: Tools for building Pyodide
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agriyakhetarpal
    - bollwyvl
