# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.30.0"

package:
  name: pyodide-build
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyodide-build/pyodide_build-${{ version }}.tar.gz
  sha256: e39076c343849d48346d030de277b9b10906a7e7bf18531f91405eaa68cfebc1
  patches:
    # this _should_ fail if the version of cmake changes below
    - 0000-no-cmake-from-pip.patch

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - auditwheel-emscripten >=0.0.9,<0.1.0
    - cmake >=3.24
    - packaging
    - pydantic >=2,<3
    - pyodide-cli >=0.2.1,<0.3.dev0
    - python >=${{ python_min }}
    - python-build >=1.2.0,<1.3.dev0
    - pyodide-lock ==0.1.0a7
    - requests
    - resolvelib
    - rich
    - ruamel.yaml
    - typer
    - unearth >=0.6,<1.dev0
    - virtualenv
    - wheel

tests:
  - python:
      python_version: ${{ python_min }}.*
      pip_check: true
      imports: pyodide_build
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pyodide build-recipes --help
      - pyodide skeleton --help
      - pyodide config --help
      - python -c "v = __import__('pyodide_build').__version__; print(v); assert v == '${{ version }}'"

about:
  summary: Tools for building Pyodide
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/pyodide/pyodide-build

extra:
  recipe-maintainers:
    - agriyakhetarpal
    - bollwyvl
